---
- name: Configure PHP8.2
  command: a2enmod proxy_fcgi setenvif

- name: Conf PHP8.2 fpm
  command: a2enconf php8.2-fpm

- name: ensure php8.2-fpm cgi.fix_pathinfo=2
  lineinfile:
    dest: /etc/php/8.2/fpm/php.ini
    regexp: "^(.*)cgi.fix_pathinfo="
    line: cgi.fix_pathinfo=0
  when: "'php8.2-fpm' in php82_modules"
  notify:
    - restart-php8.2-fpm

- name: increase php8.2-fpm memory_limit
  lineinfile:
    dest: /etc/php/8.2/fpm/php.ini
    regexp: "^(.*)memory_limit(.*)=(.*)"
    line: "memory_limit = {{ php_memory_limit }}"
  when: "'php8.2-fpm' in php82_modules"
  notify:
    - restart-php8.2-fpm

- name: increase php8.2-fpm max_input_vars
  lineinfile:
    dest: /etc/php/8.2/fpm/php.ini
    regexp: "^(.*)max_input_vars(.*)=(.*)"
    line: "max_input_vars = {{ php_max_input_vars }}"
  when: "'php8.2-fpm' in php82_modules"
  notify:
    - restart-php8.2-fpm
