# Use official Node.js image
FROM node:slim

# Set working directory inside the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json (if available)
COPY package.*json ./
# COPY index.js ./
# Copy .env ./
# Install dependencies
RUN npm install

# Copy all other project files
#COPY . .

# Expose application port
EXPOSE 3000
# Start the Node.js app
CMD ["npm", "start"]
# CMD ["node", "start.js"]
