services:
  myapplication:
    image: mongodb/mongodb-community-server:6.0-ubi8
    environment:
      CONN_STR: mongodb://user:pass@mongodb
    command: '/bin/bash -c "sleep 5; mongosh $$CONN_STR --eval \"show dbs;\""'
    depends_on:
      - mongodb
  mongodb:
    image: mongodb/mongodb-community-server
    container_name: "c2-mongoatlas"
    restart: "always"
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAM: user
      MONGO_INITDB_ROOT_PASSWORD: pass
