#FROM mysql:8
#RUN echo "[mysqld]" >> /etc/mysql/my.cnf
#RUN echo "default-authentication-plugin=mysql_native_password" >> /etc/mysql/my.cnf

FROM alpine:3.14
RUN apk add --no-cache mysql-client
ENTRYPOINT ["mysql"]
