---
- name: Update yum package cache
  yum:
    update_cache: yes

- name: Ensure Apache is installed on Centos7.
  yum:
    name: "{{ item }}"
    state: latest
  loop: "{{ apache_packages }}"
  
- name: Ensure Apache has selected state and enabled on boot.
  service:
    name: "{{ apache_service }}"
    state: "{{ apache_state }}"
    enabled: "{{ apache_enabled }}"
