#!/usr/bin/expect -f

set timeout -1
set ssh_password "dUG!6Mn5zt5i__C_"
set sudo_password "dUG!6Mn5zt5i__C_"
set script_path "install-wireguard-c7.sh"
#
spawn ssh -o StrictHostKeyChecking=no hunter@84.252.95.249 -p 22 -i ../../../Infra/ansible/playbook/ssh/files/infra 'bash -s'
expect "*password:" { send "$ssh_password\r" }
expect "*sudo password:" { send "$sudo_password\r" }
send "bash -s < $script_path\r"
interact
