- name: Generate random password for {{ ansible_user }}
  set_fact:
    random_password: "{{ lookup('community.general.random_string', length=16, min_lower=1, min_upper=2, min_numeric=3, min_special=4, override_special='-_+!#$()[]') }}"

- name: Display password for {{ ansible_user }}
  debug:
    msg: "Host: {{ inventory_hostname }} | User: {{ ansible_user }} | Password: {{ random_password }}"

- name: Add host details to list
  set_fact:
    user_details: "{{ user_details | default([]) + [{'host': inventory_hostname, 'user': ansible_user, 'port': ansible_port , 'password': random_password}] }}"

- name: Change {{ ansible_user }} password
  user:
    name: "{{ ansible_user }}"
    password: "{{ random_password | password_hash('sha512') }}"
    state: present

- name: Save pasword details for {{ ansible_user }}
  local_action:
    module: lineinfile
    path: "{{ password_output_file }}"
    line: "{{ item.host }},{{ item.user }},{{ item.password }}"
    create: yes
  delegate_to: localhost
  # run_once: true
  with_items: "{{ user_details }}"
  ignore_errors: true
# - name: Save all user passwords to file
#   local_action:
#     module: lineinfile
#     path: "{{ password_output_file }}"
#     line: "{{ item.host }},{{ item.user }},{{ item.password }}"
#     create: yes
#   delegate_to: localhost
#   run_once: false
#   with_items: "{{ user_details }}"
